name: PyTests
on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Show files
        run: ls -l
      - name: pytests
        run: |
          pip install -r requirements.txt
          pytest tests/
